### ISSUE TITLE
Facing issue while creating instance using "new ExpressOIDC"

### ISSUE THREAD

**Issue by ghost** [okta/okta-oidc-middleware#49]
### Describe the bug?

Getting this issue in NodeJS code 

GotError [RequestError]: Protocol "https:" not supported. Expected "http:"
    at get (/app/server/node_modules/got/source/request-as-event-emitter.js:236:15)
    at Immediate.<anonymous> (/app/server/node_modules/got/source/request-as-event-emitter.js:305:10) {
  code: 'ERR_INVALID_PROTOCOL',

### What is expected to happen?

No error should come here and the package should support https as well.

### What is the actual behavior?

As of now the server fails to initialise because of this issue.

### Reproduction Steps?

Shared in the `Describe the bug?` section

### SDK Versions

Using this:
"@okta/oidc-middleware": "^4.0.1",

### Execution Environment

const oidc = new ExpressOIDC({
    issuer: 'https://okta.*****.com',
    client_id: 'CLIENT_ID',
    client_secret: 'CLIENT_SECRET',
    redirect_uri: `https://www.*****.com/authorization-code/callback`,
    scope: 'openid offline_access',
    appBaseUrl: basePath,
    sessionKey: 'oktaSession',
});

**Comment by krayush** [comment]
This might help with your investigation.
I tried with Node 12.x and it seems to be working fine! Facing this issue only on Node 16.x

**Comment by krayush** [comment]
The version installed is "4.0.1" from yarn.lock file

**Comment by jaredperreault-okta** [comment]
Can you try upgrading to the latest version (4.5.1)? So far I have been unable to repro this

**Comment by krayush** [comment]
I thought of it as the first solution but that didn't work!
I did try it again today but facing the same issue again.

**Comment by jaredperreault-okta** [comment]
It would be helpful if you could provide a sample repo where the error occurs because I have been unable to reproduce this issue locally. In the meantime, we will continue to investigate this internally

Internal Ref: OKTA-505604

**Comment by jaredperreault-okta** [comment]
@krayush Are you still experiencing this issue? I have been unable to repro this in `node 16.15.1` with our test [apps](https://github.com/okta/okta-oidc-middleware/tree/master/test/e2e/harness)

**Comment by krayush** [comment]
Yes! I still have the same issue and its still not resolved!
We are doing our current rollouts via hack by downgrading the NodeJS version to 12.x
